% SCRIPT PARA GRÁFICA DE DESFASES DE SINCRONIZACIÓN
clear; clc; close all;

% Desfases absolutos medidos entre EP1 y EP2 en las 15 repeticiones
desfases_ms = [0, 44.3, 49.3, 0, 0, 0, 0, 0, 0, 55, 0, 0, 0, 77, 0];

num_pruebas = 1:length(desfases_ms);

% Parámetros del sistema de medida
fps_camara = 24;
resolucion_temporal_ms = 1000 / fps_camara;   % 41.67 ms

% Estadísticos
media_desfase = mean(desfases_ms);
desv_desfase = std(desfases_ms);
mediana_desfase = median(desfases_ms);
max_desfase = max(desfases_ms);

% Crear figura
fig = figure('Name', 'Desfase de sincronización', ...
             'Color', 'w', ...
             'Position', [100, 100, 850, 450]);

hold on; grid on; box on;

% Representación de los desfases
stem(num_pruebas, desfases_ms, ...
    'filled', ...
    'LineWidth', 1.4, ...
    'MarkerSize', 6, ...
    'Color', '#0072BD', ...
    'DisplayName', 'Desfase medido');

% Línea de resolución temporal de la cámara
yline(resolucion_temporal_ms, '--', ...
    sprintf('1 frame = %.1f ms', resolucion_temporal_ms), ...
    'LineWidth', 1.5, ...
    'Color', '#D95319', ...
    'FontSize', 10, ...
    'LabelHorizontalAlignment', 'left', ...
    'LabelVerticalAlignment', 'bottom', ...
    'DisplayName', 'Resolución temporal de la cámara');

% Línea de media
yline(media_desfase, '-.', ...
    sprintf('Media = %.1f ms', media_desfase), ...
    'LineWidth', 1.5, ...
    'Color', '#77AC30', ...
    'FontSize', 10, ...
    'LabelHorizontalAlignment', 'left', ...
    'LabelVerticalAlignment', 'top', ...
    'DisplayName', 'Media');

% Marcar en otro color los ensayos que superan un frame
idx_supera_frame = desfases_ms > resolucion_temporal_ms;
plot(num_pruebas(idx_supera_frame), desfases_ms(idx_supera_frame), ...
    'o', ...
    'MarkerSize', 8, ...
    'LineWidth', 1.5, ...
    'Color', '#A2142F', ...
    'DisplayName', 'Desfase superior a 1 frame');

% Estética
title('Desfase temporal absoluto entre robots', ...
    'FontSize', 13, ...
    'FontWeight', 'bold');

xlabel('Número de repetición', ...
    'FontSize', 11, ...
    'FontWeight', 'bold');

ylabel('Desfase temporal absoluto (ms)', ...
    'FontSize', 11, ...
    'FontWeight', 'bold');

xlim([0.5, length(desfases_ms) + 0.5]);

% Margen automático en Y para que no corte el máximo
ylim([0, max(desfases_ms) * 1.20]);

xticks(num_pruebas);

set(gca, ...
    'FontSize', 11, ...
    'GridAlpha', 0.35, ...
    'MinorGridAlpha', 0.15);

legend('Location', 'northwest');

% Texto resumen dentro de la figura
texto_resumen = sprintf(['Media = %.1f ms\n' ...
                         'Desv. típica = %.1f ms\n' ...
                         'Mediana = %.1f ms\n' ...
                         'Máximo = %.1f ms'], ...
                         media_desfase, desv_desfase, mediana_desfase, max_desfase);

text(0.73, 0.78, texto_resumen, ...
    'Units', 'normalized', ...
    'FontSize', 10, ...
    'BackgroundColor', 'white', ...
    'EdgeColor', [0.6 0.6 0.6], ...
    'Margin', 6);

% Exportar para LaTeX
exportgraphics(fig, 'dispersion_sincronismo.pdf', 'ContentType', 'vector');
exportgraphics(fig, 'dispersion_sincronismo.png', 'Resolution', 300);

disp('Gráfica generada correctamente.');
fprintf('Media: %.2f ms\n', media_desfase);
fprintf('Desviación típica: %.2f ms\n', desv_desfase);
fprintf('Mediana: %.2f ms\n', mediana_desfase);
fprintf('Máximo: %.2f ms\n', max_desfase);
fprintf('Resolución temporal cámara: %.2f ms\n', resolucion_temporal_ms);